# Generated by Django 6.0.5 on 2026-05-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_image'),
        ('vehicles', '0003_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_vehicles', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event'),
        ),
    ]
